site_name: 'Illuzionz Studios Documentation'
site_description: The Official Illuzionz Studios Documentation
site_author: Jamin Stratford
copyright: Copyright &copy; 2021 Illuzionz Studios
 

# Wiki Navigation
nav:
  - Home: index.md
  - Spigot Plugins:
    - spigot-plugins/index.md
    # - Custom Fishing:
    #   - Custom Fishing: spigot-plugins/custom-fishing/index.md
    #   - Features: spigot-plugins/custom-fishing/features.md
    #   - Installing: spigot-plugins/custom-fishing/installing.md
    #   - Configuration: spigot-plugins/custom-fishing/configuration.md
    #   - Command & Permissions: spigot-plugins/custom-fishing/commands-and-permissions.md
    #   - Developers: spigot-plugins/custom-fishing/developers.md
    - Custom Tab:
      - Custom Tab: spigot-plugins/custom-tab/index.md
      - Features: spigot-plugins/custom-tab/features.md
      - Installing: spigot-plugins/custom-tab/installing.md
      - Configuration: spigot-plugins/custom-tab/configuration.md
      - Default Files: spigot-plugins/custom-tab/default-files.md
      - Command & Permissions: spigot-plugins/custom-tab/commands-and-permissions.md
      - FAQ: spigot-plugins/custom-tab/faq.md
      - Developers: spigot-plugins/custom-tab/developers.md

# Theme
theme: 
  name: material
  language: en
  custom_dir: theme

  # Logos
  logo: assets/img/logo-full.svg
  favicon: assets/img/logo.svg

  # Fonts
  font:
    text: Inter

  features:
    - toc.integrate
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - search.suggest
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.superfences
    - pymdownx.snippets
    - content.code.annotate
  
  # Custom Icons
  icon:
    repo: fontawesome/brands/github

  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Dark Mode
    - scheme: slate

      toggle:
        icon: material/toggle-switch
        name: Light Mode

# Extra options
extra:
  generator: false

extra_css:
  - assets/stylesheets/extra.css

# Git
# repo_url: https://github.com/Illuzionz-Studios/Docs
# repo_name: Illuzionz-Studios/Docs
# edit_uri: ''

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.snippets